/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type BadRequestWithDetailData = {
    detail?: string | undefined;
};

export class BadRequestWithDetail extends Error {
    detail?: string | undefined;

    /** The original data that was passed to this error instance. */
    data$: BadRequestWithDetailData;

    constructor(err: BadRequestWithDetailData) {
        super("");
        this.data$ = err;

        if (err.detail != null) {
            this.detail = err.detail;
        }

        this.message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : "API error occurred";

        this.name = "BadRequestWithDetail";
    }
}

/** @internal */
export namespace BadRequestWithDetail$ {
    export type Inbound = {
        detail?: string | undefined;
    };

    export const inboundSchema: z.ZodType<BadRequestWithDetail, z.ZodTypeDef, Inbound> = z
        .object({
            detail: z.string().optional(),
        })
        .transform((v) => {
            return new BadRequestWithDetail({
                ...(v.detail === undefined ? null : { detail: v.detail }),
            });
        });

    export type Outbound = {
        detail?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, BadRequestWithDetail> = z
        .instanceof(BadRequestWithDetail)
        .transform((v) => v.data$)
        .pipe(
            z
                .object({
                    detail: z.string().optional(),
                })
                .transform((v) => {
                    return {
                        ...(v.detail === undefined ? null : { detail: v.detail }),
                    };
                })
        );
}
