/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transactionsCreate } from "../funcs/transactionsCreate.js";
import { transactionsGet } from "../funcs/transactionsGet.js";
import { transactionsList } from "../funcs/transactionsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Transactions extends ClientSDK {
  /**
   * List all shipping labels
   *
   * @remarks
   * Returns a list of all transaction objects.
   *
   * To filter results by creation date, use the optional query parameters below. Provided dates should be ISO 8601 UTC dates (timezone offsets are currently not supported).
   *
   * - `object_created_gt`: object(s) created after the provided date time
   * - `object_created_gte`: object(s) created at or after the provided date time
   * - `object_created_lt`: object(s) created before the provided date time
   * - `object_created_lte`: object(s) created at or before the provided date time
   *
   * Provide at most one lower bound (`object_created_gt` or `object_created_gte`) and at most one upper bound (`object_created_lt` or `object_created_lte`) per request. Lower bounds must not be in the future.
   *
   * Date format examples: `2017-01-01`, `2017-01-01T03:30:30` (or `2017-01-01T03:30:30.5`), `2017-01-01T03:30:30Z`
   *
   * Example URL: `https://api.goshippo.com/transactions/?object_created_gte=2017-01-01T00:00:30&object_created_lt=2017-04-01T00:00:30`
   */
  async list(
    request: operations.ListTransactionsRequest,
    options?: RequestOptions,
  ): Promise<components.TransactionPaginatedList> {
    return unwrapAsync(transactionsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a shipping label
   *
   * @remarks
   * Creates a new transaction object and purchases the shipping label using a rate object that has previously been created.
   *
   * Alternatively, creates a new transaction object and purchases the shipping label instantly using shipment details, an existing carrier account, and an existing service level token.
   */
  async create(
    request: operations.CreateTransactionRequestBody,
    options?: RequestOptions,
  ): Promise<components.Transaction> {
    return unwrapAsync(transactionsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a shipping label
   *
   * @remarks
   * Returns an existing transaction using an object ID.
   */
  async get(
    transactionId: string,
    options?: RequestOptions,
  ): Promise<components.Transaction> {
    return unwrapAsync(transactionsGet(
      this,
      transactionId,
      options,
    ));
  }
}
