/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the shippo SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx addressesList.example.ts
 */

import { Shippo } from "shippo";

const shippo = new Shippo({
  shippoApiVersion: "2018-02-08",
  apiKeyHeader: "<YOUR_API_KEY_HERE>",
});

async function main() {
  const result = await shippo.addresses.list();

  console.log(result);
}

main().catch(console.error);
