workflowVersion: 1.0.0
sources:
    my-first-source:
        inputs:
            - location: https://docs.goshippo.com/spec/shippoapi/public-api.yaml
targets:
    my-first-target:
        target: typescript
        source: my-first-source
