workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    openapi:
        inputs:
            - location: https://docs.goshippo.com/spec/shippoapi/public-api.yaml
        overlays:
            - location: https://docs.goshippo.com/spec/shippoapi/client-sdk-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/shippo/shippo/openapi
targets:
    first-target:
        target: typescript
        source: openapi
        publish:
            npm:
                token: $npm_token
