/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type CreateTransactionGlobals = {
  /**
   * Optional string used to pick a non-default API version to use. See our <a href="https://docs.goshippo.com/docs/api_concepts/apiversioning/">API version</a> guide.
   */
  shippoApiVersion?: string | undefined;
};

/**
 * Examples.
 */
export type CreateTransactionRequestBody =
  | components.TransactionCreateRequest
  | components.InstantTransactionCreateRequest;

/** @internal */
export const CreateTransactionGlobals$inboundSchema: z.ZodType<
  CreateTransactionGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  "SHIPPO-API-VERSION": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "SHIPPO-API-VERSION": "shippoApiVersion",
  });
});

/** @internal */
export type CreateTransactionGlobals$Outbound = {
  "SHIPPO-API-VERSION"?: string | undefined;
};

/** @internal */
export const CreateTransactionGlobals$outboundSchema: z.ZodType<
  CreateTransactionGlobals$Outbound,
  z.ZodTypeDef,
  CreateTransactionGlobals
> = z.object({
  shippoApiVersion: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    shippoApiVersion: "SHIPPO-API-VERSION",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateTransactionGlobals$ {
  /** @deprecated use `CreateTransactionGlobals$inboundSchema` instead. */
  export const inboundSchema = CreateTransactionGlobals$inboundSchema;
  /** @deprecated use `CreateTransactionGlobals$outboundSchema` instead. */
  export const outboundSchema = CreateTransactionGlobals$outboundSchema;
  /** @deprecated use `CreateTransactionGlobals$Outbound` instead. */
  export type Outbound = CreateTransactionGlobals$Outbound;
}

/** @internal */
export const CreateTransactionRequestBody$inboundSchema: z.ZodType<
  CreateTransactionRequestBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.TransactionCreateRequest$inboundSchema,
  components.InstantTransactionCreateRequest$inboundSchema,
]);

/** @internal */
export type CreateTransactionRequestBody$Outbound =
  | components.TransactionCreateRequest$Outbound
  | components.InstantTransactionCreateRequest$Outbound;

/** @internal */
export const CreateTransactionRequestBody$outboundSchema: z.ZodType<
  CreateTransactionRequestBody$Outbound,
  z.ZodTypeDef,
  CreateTransactionRequestBody
> = z.union([
  components.TransactionCreateRequest$outboundSchema,
  components.InstantTransactionCreateRequest$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateTransactionRequestBody$ {
  /** @deprecated use `CreateTransactionRequestBody$inboundSchema` instead. */
  export const inboundSchema = CreateTransactionRequestBody$inboundSchema;
  /** @deprecated use `CreateTransactionRequestBody$outboundSchema` instead. */
  export const outboundSchema = CreateTransactionRequestBody$outboundSchema;
  /** @deprecated use `CreateTransactionRequestBody$Outbound` instead. */
  export type Outbound = CreateTransactionRequestBody$Outbound;
}
