/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type CreateCustomsItemRequest = {
    /**
     * String used to pick a non-default API version to use
     */
    shippoApiVersion?: string | undefined;
    /**
     * CustomsItem details.
     */
    customsItemBase?: components.CustomsItemBase | undefined;
};

/** @internal */
export namespace CreateCustomsItemRequest$ {
    export type Inbound = {
        "SHIPPO-API-VERSION"?: string | undefined;
        CustomsItemBase?: components.CustomsItemBase$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<CreateCustomsItemRequest, z.ZodTypeDef, Inbound> = z
        .object({
            "SHIPPO-API-VERSION": z.string().optional(),
            CustomsItemBase: components.CustomsItemBase$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v["SHIPPO-API-VERSION"] === undefined
                    ? null
                    : { shippoApiVersion: v["SHIPPO-API-VERSION"] }),
                ...(v.CustomsItemBase === undefined
                    ? null
                    : { customsItemBase: v.CustomsItemBase }),
            };
        });

    export type Outbound = {
        "SHIPPO-API-VERSION"?: string | undefined;
        CustomsItemBase?: components.CustomsItemBase$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateCustomsItemRequest> = z
        .object({
            shippoApiVersion: z.string().optional(),
            customsItemBase: components.CustomsItemBase$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.shippoApiVersion === undefined
                    ? null
                    : { "SHIPPO-API-VERSION": v.shippoApiVersion }),
                ...(v.customsItemBase === undefined
                    ? null
                    : { CustomsItemBase: v.customsItemBase }),
            };
        });
}
