/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as components from "../components/index.js";

export type CreateParcelGlobals = {
  /**
   * Optional string used to pick a non-default API version to use. See our <a href="https://docs.goshippo.com/docs/api_concepts/apiversioning/">API version</a> guide.
   */
  shippoApiVersion?: string | undefined;
};

/**
 * Parcel details.
 */
export type CreateParcelRequestBody =
  | components.ParcelCreateRequest
  | components.ParcelCreateFromTemplateRequest;

/** @internal */
export type CreateParcelRequestBody$Outbound =
  | components.ParcelCreateRequest$Outbound
  | components.ParcelCreateFromTemplateRequest$Outbound;

/** @internal */
export const CreateParcelRequestBody$outboundSchema: z.ZodMiniType<
  CreateParcelRequestBody$Outbound,
  CreateParcelRequestBody
> = z.union([
  components.ParcelCreateRequest$outboundSchema,
  components.ParcelCreateFromTemplateRequest$outboundSchema,
]);

export function createParcelRequestBodyToJSON(
  createParcelRequestBody: CreateParcelRequestBody,
): string {
  return JSON.stringify(
    CreateParcelRequestBody$outboundSchema.parse(createParcelRequestBody),
  );
}
