/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type CreateCarrierAccountGlobals = {
  /**
   * Optional string used to pick a non-default API version to use. See our [API version](https://docs.goshippo.com/docs/api_concepts/apiversioning/) guide.
   */
  shippoApiVersion?: string | undefined;
};
