/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteDefaultParcelTemplateGlobals = {
    /**
     * String used to pick a non-default API version to use
     */
    shippoApiVersion?: string | undefined;
};

export type DeleteDefaultParcelTemplateRequest = {};

/** @internal */
export namespace DeleteDefaultParcelTemplateGlobals$ {
    export const inboundSchema: z.ZodType<
        DeleteDefaultParcelTemplateGlobals,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            "SHIPPO-API-VERSION": z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v["SHIPPO-API-VERSION"] === undefined
                    ? null
                    : { shippoApiVersion: v["SHIPPO-API-VERSION"] }),
            };
        });

    export type Outbound = {
        "SHIPPO-API-VERSION"?: string | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        DeleteDefaultParcelTemplateGlobals
    > = z
        .object({
            shippoApiVersion: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.shippoApiVersion === undefined
                    ? null
                    : { "SHIPPO-API-VERSION": v.shippoApiVersion }),
            };
        });
}

/** @internal */
export namespace DeleteDefaultParcelTemplateRequest$ {
    export const inboundSchema: z.ZodType<
        DeleteDefaultParcelTemplateRequest,
        z.ZodTypeDef,
        unknown
    > = z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        DeleteDefaultParcelTemplateRequest
    > = z.object({});
}
