/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetAddressGlobals = {
  /**
   * Optional string used to pick a non-default API version to use. See our <a href="https://docs.goshippo.com/docs/api_concepts/apiversioning/">API version</a> guide.
   */
  shippoApiVersion?: string | undefined;
};

export type GetAddressRequest = {
  /**
   * Object ID of the address
   */
  addressId: string;
};

/** @internal */
export type GetAddressRequest$Outbound = {
  AddressId: string;
};

/** @internal */
export const GetAddressRequest$outboundSchema: z.ZodMiniType<
  GetAddressRequest$Outbound,
  GetAddressRequest
> = z.pipe(
  z.object({
    addressId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      addressId: "AddressId",
    });
  }),
);

export function getAddressRequestToJSON(
  getAddressRequest: GetAddressRequest,
): string {
  return JSON.stringify(
    GetAddressRequest$outboundSchema.parse(getAddressRequest),
  );
}
