/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetCarrierParcelTemplateGlobals = {
  /**
   * Optional string used to pick a non-default API version to use. See our <a href="https://docs.goshippo.com/docs/api_concepts/apiversioning/">API version</a> guide.
   */
  shippoApiVersion?: string | undefined;
};

export type GetCarrierParcelTemplateRequest = {
  /**
   * The unique string representation of the carrier parcel template
   */
  carrierParcelTemplateToken: string;
};

/** @internal */
export const GetCarrierParcelTemplateGlobals$inboundSchema: z.ZodType<
  GetCarrierParcelTemplateGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  "SHIPPO-API-VERSION": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "SHIPPO-API-VERSION": "shippoApiVersion",
  });
});

/** @internal */
export type GetCarrierParcelTemplateGlobals$Outbound = {
  "SHIPPO-API-VERSION"?: string | undefined;
};

/** @internal */
export const GetCarrierParcelTemplateGlobals$outboundSchema: z.ZodType<
  GetCarrierParcelTemplateGlobals$Outbound,
  z.ZodTypeDef,
  GetCarrierParcelTemplateGlobals
> = z.object({
  shippoApiVersion: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    shippoApiVersion: "SHIPPO-API-VERSION",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCarrierParcelTemplateGlobals$ {
  /** @deprecated use `GetCarrierParcelTemplateGlobals$inboundSchema` instead. */
  export const inboundSchema = GetCarrierParcelTemplateGlobals$inboundSchema;
  /** @deprecated use `GetCarrierParcelTemplateGlobals$outboundSchema` instead. */
  export const outboundSchema = GetCarrierParcelTemplateGlobals$outboundSchema;
  /** @deprecated use `GetCarrierParcelTemplateGlobals$Outbound` instead. */
  export type Outbound = GetCarrierParcelTemplateGlobals$Outbound;
}

export function getCarrierParcelTemplateGlobalsToJSON(
  getCarrierParcelTemplateGlobals: GetCarrierParcelTemplateGlobals,
): string {
  return JSON.stringify(
    GetCarrierParcelTemplateGlobals$outboundSchema.parse(
      getCarrierParcelTemplateGlobals,
    ),
  );
}

export function getCarrierParcelTemplateGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<GetCarrierParcelTemplateGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCarrierParcelTemplateGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCarrierParcelTemplateGlobals' from JSON`,
  );
}

/** @internal */
export const GetCarrierParcelTemplateRequest$inboundSchema: z.ZodType<
  GetCarrierParcelTemplateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  CarrierParcelTemplateToken: z.string(),
}).transform((v) => {
  return remap$(v, {
    "CarrierParcelTemplateToken": "carrierParcelTemplateToken",
  });
});

/** @internal */
export type GetCarrierParcelTemplateRequest$Outbound = {
  CarrierParcelTemplateToken: string;
};

/** @internal */
export const GetCarrierParcelTemplateRequest$outboundSchema: z.ZodType<
  GetCarrierParcelTemplateRequest$Outbound,
  z.ZodTypeDef,
  GetCarrierParcelTemplateRequest
> = z.object({
  carrierParcelTemplateToken: z.string(),
}).transform((v) => {
  return remap$(v, {
    carrierParcelTemplateToken: "CarrierParcelTemplateToken",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCarrierParcelTemplateRequest$ {
  /** @deprecated use `GetCarrierParcelTemplateRequest$inboundSchema` instead. */
  export const inboundSchema = GetCarrierParcelTemplateRequest$inboundSchema;
  /** @deprecated use `GetCarrierParcelTemplateRequest$outboundSchema` instead. */
  export const outboundSchema = GetCarrierParcelTemplateRequest$outboundSchema;
  /** @deprecated use `GetCarrierParcelTemplateRequest$Outbound` instead. */
  export type Outbound = GetCarrierParcelTemplateRequest$Outbound;
}

export function getCarrierParcelTemplateRequestToJSON(
  getCarrierParcelTemplateRequest: GetCarrierParcelTemplateRequest,
): string {
  return JSON.stringify(
    GetCarrierParcelTemplateRequest$outboundSchema.parse(
      getCarrierParcelTemplateRequest,
    ),
  );
}

export function getCarrierParcelTemplateRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetCarrierParcelTemplateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCarrierParcelTemplateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCarrierParcelTemplateRequest' from JSON`,
  );
}
