/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type GetDefaultParcelTemplateRequest = {};

/** @internal */
export namespace GetDefaultParcelTemplateRequest$ {
    export const inboundSchema: z.ZodType<GetDefaultParcelTemplateRequest, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetDefaultParcelTemplateRequest
    > = z.object({});
}
