/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetRateGlobals = {
  /**
   * Optional string used to pick a non-default API version to use. See our <a href="https://docs.goshippo.com/docs/api_concepts/apiversioning/">API version</a> guide.
   */
  shippoApiVersion?: string | undefined;
};

export type GetRateRequest = {
  /**
   * Object ID of the rate
   */
  rateId: string;
};

/** @internal */
export type GetRateRequest$Outbound = {
  RateId: string;
};

/** @internal */
export const GetRateRequest$outboundSchema: z.ZodMiniType<
  GetRateRequest$Outbound,
  GetRateRequest
> = z.pipe(
  z.object({
    rateId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      rateId: "RateId",
    });
  }),
);

export function getRateRequestToJSON(getRateRequest: GetRateRequest): string {
  return JSON.stringify(GetRateRequest$outboundSchema.parse(getRateRequest));
}
