/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type GetRateGlobals = {
    /**
     * String used to pick a non-default API version to use
     */
    shippoApiVersion?: string | undefined;
};

export type GetRateRequest = {
    /**
     * Object ID of the rate
     */
    rateId: string;
};

/** @internal */
export namespace GetRateGlobals$ {
    export const inboundSchema: z.ZodType<GetRateGlobals, z.ZodTypeDef, unknown> = z
        .object({
            "SHIPPO-API-VERSION": z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v["SHIPPO-API-VERSION"] === undefined
                    ? null
                    : { shippoApiVersion: v["SHIPPO-API-VERSION"] }),
            };
        });

    export type Outbound = {
        "SHIPPO-API-VERSION"?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetRateGlobals> = z
        .object({
            shippoApiVersion: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.shippoApiVersion === undefined
                    ? null
                    : { "SHIPPO-API-VERSION": v.shippoApiVersion }),
            };
        });
}

/** @internal */
export namespace GetRateRequest$ {
    export const inboundSchema: z.ZodType<GetRateRequest, z.ZodTypeDef, unknown> = z
        .object({
            RateId: z.string(),
        })
        .transform((v) => {
            return {
                rateId: v.RateId,
            };
        });

    export type Outbound = {
        RateId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetRateRequest> = z
        .object({
            rateId: z.string(),
        })
        .transform((v) => {
            return {
                RateId: v.rateId,
            };
        });
}
