/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetShipmentGlobals = {
  /**
   * Optional string used to pick a non-default API version to use. See our <a href="https://docs.goshippo.com/docs/api_concepts/apiversioning/">API version</a> guide.
   */
  shippoApiVersion?: string | undefined;
};

export type GetShipmentRequest = {
  /**
   * Object ID of the shipment to update
   */
  shipmentId: string;
};

/** @internal */
export const GetShipmentGlobals$inboundSchema: z.ZodType<
  GetShipmentGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  "SHIPPO-API-VERSION": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "SHIPPO-API-VERSION": "shippoApiVersion",
  });
});

/** @internal */
export type GetShipmentGlobals$Outbound = {
  "SHIPPO-API-VERSION"?: string | undefined;
};

/** @internal */
export const GetShipmentGlobals$outboundSchema: z.ZodType<
  GetShipmentGlobals$Outbound,
  z.ZodTypeDef,
  GetShipmentGlobals
> = z.object({
  shippoApiVersion: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    shippoApiVersion: "SHIPPO-API-VERSION",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetShipmentGlobals$ {
  /** @deprecated use `GetShipmentGlobals$inboundSchema` instead. */
  export const inboundSchema = GetShipmentGlobals$inboundSchema;
  /** @deprecated use `GetShipmentGlobals$outboundSchema` instead. */
  export const outboundSchema = GetShipmentGlobals$outboundSchema;
  /** @deprecated use `GetShipmentGlobals$Outbound` instead. */
  export type Outbound = GetShipmentGlobals$Outbound;
}

/** @internal */
export const GetShipmentRequest$inboundSchema: z.ZodType<
  GetShipmentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ShipmentId: z.string(),
}).transform((v) => {
  return remap$(v, {
    "ShipmentId": "shipmentId",
  });
});

/** @internal */
export type GetShipmentRequest$Outbound = {
  ShipmentId: string;
};

/** @internal */
export const GetShipmentRequest$outboundSchema: z.ZodType<
  GetShipmentRequest$Outbound,
  z.ZodTypeDef,
  GetShipmentRequest
> = z.object({
  shipmentId: z.string(),
}).transform((v) => {
  return remap$(v, {
    shipmentId: "ShipmentId",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetShipmentRequest$ {
  /** @deprecated use `GetShipmentRequest$inboundSchema` instead. */
  export const inboundSchema = GetShipmentRequest$inboundSchema;
  /** @deprecated use `GetShipmentRequest$outboundSchema` instead. */
  export const outboundSchema = GetShipmentRequest$outboundSchema;
  /** @deprecated use `GetShipmentRequest$Outbound` instead. */
  export type Outbound = GetShipmentRequest$Outbound;
}
