/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type ListTransactionsGlobals = {
    /**
     * String used to pick a non-default API version to use
     */
    shippoApiVersion?: string | undefined;
};

export type ListTransactionsRequest = {
    /**
     * Filter by rate ID
     */
    rate?: string | undefined;
    /**
     * Filter by object status
     */
    objectStatus?: components.TransactionStatusEnum | undefined;
    /**
     * Filter by tracking status
     */
    trackingStatus?: components.TrackingStatusEnum | undefined;
    /**
     * The page number you want to select
     */
    page?: number | undefined;
    /**
     * The number of results to return per page (max 100)
     */
    results?: number | undefined;
};

/** @internal */
export namespace ListTransactionsGlobals$ {
    export const inboundSchema: z.ZodType<ListTransactionsGlobals, z.ZodTypeDef, unknown> = z
        .object({
            "SHIPPO-API-VERSION": z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v["SHIPPO-API-VERSION"] === undefined
                    ? null
                    : { shippoApiVersion: v["SHIPPO-API-VERSION"] }),
            };
        });

    export type Outbound = {
        "SHIPPO-API-VERSION"?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListTransactionsGlobals> = z
        .object({
            shippoApiVersion: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.shippoApiVersion === undefined
                    ? null
                    : { "SHIPPO-API-VERSION": v.shippoApiVersion }),
            };
        });
}

/** @internal */
export namespace ListTransactionsRequest$ {
    export const inboundSchema: z.ZodType<ListTransactionsRequest, z.ZodTypeDef, unknown> = z
        .object({
            rate: z.string().optional(),
            object_status: components.TransactionStatusEnum$.inboundSchema.optional(),
            tracking_status: components.TrackingStatusEnum$.inboundSchema.optional(),
            page: z.number().int().default(1),
            results: z.number().int().default(25),
        })
        .transform((v) => {
            return {
                ...(v.rate === undefined ? null : { rate: v.rate }),
                ...(v.object_status === undefined ? null : { objectStatus: v.object_status }),
                ...(v.tracking_status === undefined ? null : { trackingStatus: v.tracking_status }),
                page: v.page,
                results: v.results,
            };
        });

    export type Outbound = {
        rate?: string | undefined;
        object_status?: string | undefined;
        tracking_status?: string | undefined;
        page: number;
        results: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListTransactionsRequest> = z
        .object({
            rate: z.string().optional(),
            objectStatus: components.TransactionStatusEnum$.outboundSchema.optional(),
            trackingStatus: components.TrackingStatusEnum$.outboundSchema.optional(),
            page: z.number().int().default(1),
            results: z.number().int().default(25),
        })
        .transform((v) => {
            return {
                ...(v.rate === undefined ? null : { rate: v.rate }),
                ...(v.objectStatus === undefined ? null : { object_status: v.objectStatus }),
                ...(v.trackingStatus === undefined ? null : { tracking_status: v.trackingStatus }),
                page: v.page,
                results: v.results,
            };
        });
}
