/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export type ListCarrierParcelTemplatesGlobals = {
  /**
   * Optional string used to pick a non-default API version to use. See our <a href="https://docs.goshippo.com/docs/api_concepts/apiversioning/">API version</a> guide.
   */
  shippoApiVersion?: string | undefined;
};

/**
 * filter by user or enabled
 */
export const Include = {
  All: "all",
  User: "user",
  Enabled: "enabled",
} as const;
/**
 * filter by user or enabled
 */
export type Include = ClosedEnum<typeof Include>;

export type ListCarrierParcelTemplatesRequest = {
  /**
   * filter by user or enabled
   */
  include?: Include | undefined;
  /**
   * filter by specific carrier
   */
  carrier?: string | undefined;
};

/** @internal */
export const Include$outboundSchema: z.ZodMiniEnum<typeof Include> = z.enum(
  Include,
);

/** @internal */
export type ListCarrierParcelTemplatesRequest$Outbound = {
  include?: string | undefined;
  carrier?: string | undefined;
};

/** @internal */
export const ListCarrierParcelTemplatesRequest$outboundSchema: z.ZodMiniType<
  ListCarrierParcelTemplatesRequest$Outbound,
  ListCarrierParcelTemplatesRequest
> = z.object({
  include: z.optional(Include$outboundSchema),
  carrier: z.optional(z.string()),
});

export function listCarrierParcelTemplatesRequestToJSON(
  listCarrierParcelTemplatesRequest: ListCarrierParcelTemplatesRequest,
): string {
  return JSON.stringify(
    ListCarrierParcelTemplatesRequest$outboundSchema.parse(
      listCarrierParcelTemplatesRequest,
    ),
  );
}
