/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListCustomsDeclarationsGlobals = {
  /**
   * Optional string used to pick a non-default API version to use. See our <a href="https://docs.goshippo.com/docs/api_concepts/apiversioning/">API version</a> guide.
   */
  shippoApiVersion?: string | undefined;
};

export type ListCustomsDeclarationsRequest = {
  /**
   * The page number you want to select
   */
  page?: number | undefined;
  /**
   * The number of results to return per page (max 100, default 5)
   */
  results?: number | undefined;
};

/** @internal */
export type ListCustomsDeclarationsRequest$Outbound = {
  page: number;
  results: number;
};

/** @internal */
export const ListCustomsDeclarationsRequest$outboundSchema: z.ZodMiniType<
  ListCustomsDeclarationsRequest$Outbound,
  ListCustomsDeclarationsRequest
> = z.object({
  page: z._default(z.int(), 1),
  results: z._default(z.int(), 5),
});

export function listCustomsDeclarationsRequestToJSON(
  listCustomsDeclarationsRequest: ListCustomsDeclarationsRequest,
): string {
  return JSON.stringify(
    ListCustomsDeclarationsRequest$outboundSchema.parse(
      listCustomsDeclarationsRequest,
    ),
  );
}
