/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type ValidateAddressGlobals = {
  /**
   * Optional string used to pick a non-default API version to use. See our <a href="https://docs.goshippo.com/docs/api_concepts/apiversioning/">API version</a> guide.
   */
  shippoApiVersion?: string | undefined;
};

export type ValidateAddressRequest = {
  /**
   * Object ID of the address
   */
  addressId: string;
};

/** @internal */
export type ValidateAddressRequest$Outbound = {
  AddressId: string;
};

/** @internal */
export const ValidateAddressRequest$outboundSchema: z.ZodMiniType<
  ValidateAddressRequest$Outbound,
  ValidateAddressRequest
> = z.pipe(
  z.object({
    addressId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      addressId: "AddressId",
    });
  }),
);

export function validateAddressRequestToJSON(
  validateAddressRequest: ValidateAddressRequest,
): string {
  return JSON.stringify(
    ValidateAddressRequest$outboundSchema.parse(validateAddressRequest),
  );
}
