/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type CarrierAccountPosteItalianeCreateRequestParameters = {};

export type CarrierAccountPosteItalianeCreateRequest = {
    carrier: string;
    parameters: CarrierAccountPosteItalianeCreateRequestParameters;
};

/** @internal */
export namespace CarrierAccountPosteItalianeCreateRequestParameters$ {
    export const inboundSchema: z.ZodType<
        CarrierAccountPosteItalianeCreateRequestParameters,
        z.ZodTypeDef,
        unknown
    > = z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CarrierAccountPosteItalianeCreateRequestParameters
    > = z.object({});
}

/** @internal */
export namespace CarrierAccountPosteItalianeCreateRequest$ {
    export const inboundSchema: z.ZodType<
        CarrierAccountPosteItalianeCreateRequest,
        z.ZodTypeDef,
        unknown
    > = z.object({
        carrier: z.string(),
        parameters: z.lazy(() => CarrierAccountPosteItalianeCreateRequestParameters$.inboundSchema),
    });

    export type Outbound = {
        carrier: string;
        parameters: CarrierAccountPosteItalianeCreateRequestParameters$.Outbound;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CarrierAccountPosteItalianeCreateRequest
    > = z.object({
        carrier: z.string(),
        parameters: z.lazy(
            () => CarrierAccountPosteItalianeCreateRequestParameters$.outboundSchema
        ),
    });
}
