/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type CarrierAccountCanadaPostCreateParameters = {
  /**
   * Whether or not the user agrees to Canada Post's terms. If passed in as false, request will fail with error 400
   */
  canadaPostTerms: boolean;
  company: string;
  email: string;
  fullName: string;
  /**
   * Needs to be a valid phone number and cannot be null
   */
  phone: string;
};

/** @internal */
export type CarrierAccountCanadaPostCreateParameters$Outbound = {
  canada_post_terms: boolean;
  company: string;
  email: string;
  full_name: string;
  phone: string;
};

/** @internal */
export const CarrierAccountCanadaPostCreateParameters$outboundSchema:
  z.ZodMiniType<
    CarrierAccountCanadaPostCreateParameters$Outbound,
    CarrierAccountCanadaPostCreateParameters
  > = z.pipe(
    z.object({
      canadaPostTerms: z.boolean(),
      company: z.string(),
      email: z.string(),
      fullName: z.string(),
      phone: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        canadaPostTerms: "canada_post_terms",
        fullName: "full_name",
      });
    }),
  );

export function carrierAccountCanadaPostCreateParametersToJSON(
  carrierAccountCanadaPostCreateParameters:
    CarrierAccountCanadaPostCreateParameters,
): string {
  return JSON.stringify(
    CarrierAccountCanadaPostCreateParameters$outboundSchema.parse(
      carrierAccountCanadaPostCreateParameters,
    ),
  );
}
