/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type CarrierAccountDHLExpressCreateRequestParameters = {
  /**
   * Whether or not the user agrees to the DHL Express Terms and Conditions. If passed in as false, request will fail with error 400
   */
  userAcceptedTermsAndConditions: boolean;
};

/** @internal */
export type CarrierAccountDHLExpressCreateRequestParameters$Outbound = {
  user_accepted_terms_and_conditions: boolean;
};

/** @internal */
export const CarrierAccountDHLExpressCreateRequestParameters$outboundSchema:
  z.ZodMiniType<
    CarrierAccountDHLExpressCreateRequestParameters$Outbound,
    CarrierAccountDHLExpressCreateRequestParameters
  > = z.pipe(
    z.object({
      userAcceptedTermsAndConditions: z.boolean(),
    }),
    z.transform((v) => {
      return remap$(v, {
        userAcceptedTermsAndConditions: "user_accepted_terms_and_conditions",
      });
    }),
  );

export function carrierAccountDHLExpressCreateRequestParametersToJSON(
  carrierAccountDHLExpressCreateRequestParameters:
    CarrierAccountDHLExpressCreateRequestParameters,
): string {
  return JSON.stringify(
    CarrierAccountDHLExpressCreateRequestParameters$outboundSchema.parse(
      carrierAccountDHLExpressCreateRequestParameters,
    ),
  );
}
