/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CarrierParcelTemplate,
  CarrierParcelTemplate$inboundSchema,
} from "./carrierparceltemplate.js";

export type CarrierParcelTemplateList = {
  results?: Array<CarrierParcelTemplate> | undefined;
};

/** @internal */
export const CarrierParcelTemplateList$inboundSchema: z.ZodMiniType<
  CarrierParcelTemplateList,
  unknown
> = z.object({
  results: z.optional(z.array(CarrierParcelTemplate$inboundSchema)),
});

export function carrierParcelTemplateListFromJSON(
  jsonString: string,
): SafeParseResult<CarrierParcelTemplateList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CarrierParcelTemplateList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CarrierParcelTemplateList' from JSON`,
  );
}
