/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CarrierAccountDpdDeCreateRequestParameters = {};

export type CarrierAccountDpdDeCreateRequest = {
  carrier: string;
  parameters: CarrierAccountDpdDeCreateRequestParameters;
};

/** @internal */
export const CarrierAccountDpdDeCreateRequestParameters$inboundSchema:
  z.ZodType<CarrierAccountDpdDeCreateRequestParameters, z.ZodTypeDef, unknown> =
    z.object({});

/** @internal */
export type CarrierAccountDpdDeCreateRequestParameters$Outbound = {};

/** @internal */
export const CarrierAccountDpdDeCreateRequestParameters$outboundSchema:
  z.ZodType<
    CarrierAccountDpdDeCreateRequestParameters$Outbound,
    z.ZodTypeDef,
    CarrierAccountDpdDeCreateRequestParameters
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CarrierAccountDpdDeCreateRequestParameters$ {
  /** @deprecated use `CarrierAccountDpdDeCreateRequestParameters$inboundSchema` instead. */
  export const inboundSchema =
    CarrierAccountDpdDeCreateRequestParameters$inboundSchema;
  /** @deprecated use `CarrierAccountDpdDeCreateRequestParameters$outboundSchema` instead. */
  export const outboundSchema =
    CarrierAccountDpdDeCreateRequestParameters$outboundSchema;
  /** @deprecated use `CarrierAccountDpdDeCreateRequestParameters$Outbound` instead. */
  export type Outbound = CarrierAccountDpdDeCreateRequestParameters$Outbound;
}

/** @internal */
export const CarrierAccountDpdDeCreateRequest$inboundSchema: z.ZodType<
  CarrierAccountDpdDeCreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  carrier: z.string(),
  parameters: z.lazy(() =>
    CarrierAccountDpdDeCreateRequestParameters$inboundSchema
  ),
});

/** @internal */
export type CarrierAccountDpdDeCreateRequest$Outbound = {
  carrier: string;
  parameters: CarrierAccountDpdDeCreateRequestParameters$Outbound;
};

/** @internal */
export const CarrierAccountDpdDeCreateRequest$outboundSchema: z.ZodType<
  CarrierAccountDpdDeCreateRequest$Outbound,
  z.ZodTypeDef,
  CarrierAccountDpdDeCreateRequest
> = z.object({
  carrier: z.string(),
  parameters: z.lazy(() =>
    CarrierAccountDpdDeCreateRequestParameters$outboundSchema
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CarrierAccountDpdDeCreateRequest$ {
  /** @deprecated use `CarrierAccountDpdDeCreateRequest$inboundSchema` instead. */
  export const inboundSchema = CarrierAccountDpdDeCreateRequest$inboundSchema;
  /** @deprecated use `CarrierAccountDpdDeCreateRequest$outboundSchema` instead. */
  export const outboundSchema = CarrierAccountDpdDeCreateRequest$outboundSchema;
  /** @deprecated use `CarrierAccountDpdDeCreateRequest$Outbound` instead. */
  export type Outbound = CarrierAccountDpdDeCreateRequest$Outbound;
}
