/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CarrierAccountCorreosCreateRequestParameters = {};

export type CarrierAccountCorreosCreateRequest = {
  carrier: "correos";
  parameters: CarrierAccountCorreosCreateRequestParameters;
};

/** @internal */
export type CarrierAccountCorreosCreateRequestParameters$Outbound = {};

/** @internal */
export const CarrierAccountCorreosCreateRequestParameters$outboundSchema:
  z.ZodMiniType<
    CarrierAccountCorreosCreateRequestParameters$Outbound,
    CarrierAccountCorreosCreateRequestParameters
  > = z.object({});

export function carrierAccountCorreosCreateRequestParametersToJSON(
  carrierAccountCorreosCreateRequestParameters:
    CarrierAccountCorreosCreateRequestParameters,
): string {
  return JSON.stringify(
    CarrierAccountCorreosCreateRequestParameters$outboundSchema.parse(
      carrierAccountCorreosCreateRequestParameters,
    ),
  );
}

/** @internal */
export type CarrierAccountCorreosCreateRequest$Outbound = {
  carrier: "correos";
  parameters: CarrierAccountCorreosCreateRequestParameters$Outbound;
};

/** @internal */
export const CarrierAccountCorreosCreateRequest$outboundSchema: z.ZodMiniType<
  CarrierAccountCorreosCreateRequest$Outbound,
  CarrierAccountCorreosCreateRequest
> = z.object({
  carrier: z.literal("correos"),
  parameters: z.lazy(() =>
    CarrierAccountCorreosCreateRequestParameters$outboundSchema
  ),
});

export function carrierAccountCorreosCreateRequestToJSON(
  carrierAccountCorreosCreateRequest: CarrierAccountCorreosCreateRequest,
): string {
  return JSON.stringify(
    CarrierAccountCorreosCreateRequest$outboundSchema.parse(
      carrierAccountCorreosCreateRequest,
    ),
  );
}
