/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CarrierAccountRegistrationStatus = {
  carrierAccount?: string | undefined;
  objectCreated?: Date | undefined;
  objectOwner?: string | undefined;
  objectUpdated?: Date | undefined;
  status?: string | undefined;
};

/** @internal */
export const CarrierAccountRegistrationStatus$inboundSchema: z.ZodMiniType<
  CarrierAccountRegistrationStatus,
  unknown
> = z.pipe(
  z.object({
    carrier_account: z.optional(z.string()),
    object_created: z.optional(
      z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
    ),
    object_owner: z.optional(z.string()),
    object_updated: z.optional(
      z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
    ),
    status: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "carrier_account": "carrierAccount",
      "object_created": "objectCreated",
      "object_owner": "objectOwner",
      "object_updated": "objectUpdated",
    });
  }),
);

export function carrierAccountRegistrationStatusFromJSON(
  jsonString: string,
): SafeParseResult<CarrierAccountRegistrationStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CarrierAccountRegistrationStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CarrierAccountRegistrationStatus' from JSON`,
  );
}
