/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CarrierAccountDPDUKCreateRequestParameters = {};

export type CarrierAccountDPDUKCreateRequest = {
  carrier?: "dpd_uk" | undefined;
  parameters: CarrierAccountDPDUKCreateRequestParameters;
};

/** @internal */
export const CarrierAccountDPDUKCreateRequestParameters$inboundSchema:
  z.ZodType<CarrierAccountDPDUKCreateRequestParameters, z.ZodTypeDef, unknown> =
    z.object({});

/** @internal */
export type CarrierAccountDPDUKCreateRequestParameters$Outbound = {};

/** @internal */
export const CarrierAccountDPDUKCreateRequestParameters$outboundSchema:
  z.ZodType<
    CarrierAccountDPDUKCreateRequestParameters$Outbound,
    z.ZodTypeDef,
    CarrierAccountDPDUKCreateRequestParameters
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CarrierAccountDPDUKCreateRequestParameters$ {
  /** @deprecated use `CarrierAccountDPDUKCreateRequestParameters$inboundSchema` instead. */
  export const inboundSchema =
    CarrierAccountDPDUKCreateRequestParameters$inboundSchema;
  /** @deprecated use `CarrierAccountDPDUKCreateRequestParameters$outboundSchema` instead. */
  export const outboundSchema =
    CarrierAccountDPDUKCreateRequestParameters$outboundSchema;
  /** @deprecated use `CarrierAccountDPDUKCreateRequestParameters$Outbound` instead. */
  export type Outbound = CarrierAccountDPDUKCreateRequestParameters$Outbound;
}

export function carrierAccountDPDUKCreateRequestParametersToJSON(
  carrierAccountDPDUKCreateRequestParameters:
    CarrierAccountDPDUKCreateRequestParameters,
): string {
  return JSON.stringify(
    CarrierAccountDPDUKCreateRequestParameters$outboundSchema.parse(
      carrierAccountDPDUKCreateRequestParameters,
    ),
  );
}

export function carrierAccountDPDUKCreateRequestParametersFromJSON(
  jsonString: string,
): SafeParseResult<
  CarrierAccountDPDUKCreateRequestParameters,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CarrierAccountDPDUKCreateRequestParameters$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CarrierAccountDPDUKCreateRequestParameters' from JSON`,
  );
}

/** @internal */
export const CarrierAccountDPDUKCreateRequest$inboundSchema: z.ZodType<
  CarrierAccountDPDUKCreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  carrier: z.literal("dpd_uk").optional(),
  parameters: z.lazy(() =>
    CarrierAccountDPDUKCreateRequestParameters$inboundSchema
  ),
});

/** @internal */
export type CarrierAccountDPDUKCreateRequest$Outbound = {
  carrier: "dpd_uk";
  parameters: CarrierAccountDPDUKCreateRequestParameters$Outbound;
};

/** @internal */
export const CarrierAccountDPDUKCreateRequest$outboundSchema: z.ZodType<
  CarrierAccountDPDUKCreateRequest$Outbound,
  z.ZodTypeDef,
  CarrierAccountDPDUKCreateRequest
> = z.object({
  carrier: z.literal("dpd_uk").default("dpd_uk" as const),
  parameters: z.lazy(() =>
    CarrierAccountDPDUKCreateRequestParameters$outboundSchema
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CarrierAccountDPDUKCreateRequest$ {
  /** @deprecated use `CarrierAccountDPDUKCreateRequest$inboundSchema` instead. */
  export const inboundSchema = CarrierAccountDPDUKCreateRequest$inboundSchema;
  /** @deprecated use `CarrierAccountDPDUKCreateRequest$outboundSchema` instead. */
  export const outboundSchema = CarrierAccountDPDUKCreateRequest$outboundSchema;
  /** @deprecated use `CarrierAccountDPDUKCreateRequest$Outbound` instead. */
  export type Outbound = CarrierAccountDPDUKCreateRequest$Outbound;
}

export function carrierAccountDPDUKCreateRequestToJSON(
  carrierAccountDPDUKCreateRequest: CarrierAccountDPDUKCreateRequest,
): string {
  return JSON.stringify(
    CarrierAccountDPDUKCreateRequest$outboundSchema.parse(
      carrierAccountDPDUKCreateRequest,
    ),
  );
}

export function carrierAccountDPDUKCreateRequestFromJSON(
  jsonString: string,
): SafeParseResult<CarrierAccountDPDUKCreateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CarrierAccountDPDUKCreateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CarrierAccountDPDUKCreateRequest' from JSON`,
  );
}
