/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  FedExConnectExistingOwnAccountParameters,
  FedExConnectExistingOwnAccountParameters$Outbound,
  FedExConnectExistingOwnAccountParameters$outboundSchema,
} from "./fedexconnectexistingownaccountparameters.js";
import {
  UPSConnectExistingOwnAccountParameters,
  UPSConnectExistingOwnAccountParameters$Outbound,
  UPSConnectExistingOwnAccountParameters$outboundSchema,
} from "./upsconnectexistingownaccountparameters.js";

export type ConnectExistingOwnAccountRequestParameters =
  | UPSConnectExistingOwnAccountParameters
  | FedExConnectExistingOwnAccountParameters
  | { [k: string]: any };

export type ConnectExistingOwnAccountRequest = {
  accountId: string;
  active?: boolean | undefined;
  carrier: string;
  metadata?: string | undefined;
  parameters:
    | UPSConnectExistingOwnAccountParameters
    | FedExConnectExistingOwnAccountParameters
    | { [k: string]: any };
  test?: boolean | undefined;
};

/** @internal */
export type ConnectExistingOwnAccountRequestParameters$Outbound =
  | UPSConnectExistingOwnAccountParameters$Outbound
  | FedExConnectExistingOwnAccountParameters$Outbound
  | { [k: string]: any };

/** @internal */
export const ConnectExistingOwnAccountRequestParameters$outboundSchema:
  z.ZodMiniType<
    ConnectExistingOwnAccountRequestParameters$Outbound,
    ConnectExistingOwnAccountRequestParameters
  > = z.union([
    UPSConnectExistingOwnAccountParameters$outboundSchema,
    FedExConnectExistingOwnAccountParameters$outboundSchema,
    z.record(z.string(), z.any()),
  ]);

export function connectExistingOwnAccountRequestParametersToJSON(
  connectExistingOwnAccountRequestParameters:
    ConnectExistingOwnAccountRequestParameters,
): string {
  return JSON.stringify(
    ConnectExistingOwnAccountRequestParameters$outboundSchema.parse(
      connectExistingOwnAccountRequestParameters,
    ),
  );
}

/** @internal */
export type ConnectExistingOwnAccountRequest$Outbound = {
  account_id: string;
  active?: boolean | undefined;
  carrier: string;
  metadata?: string | undefined;
  parameters:
    | UPSConnectExistingOwnAccountParameters$Outbound
    | FedExConnectExistingOwnAccountParameters$Outbound
    | { [k: string]: any };
  test?: boolean | undefined;
};

/** @internal */
export const ConnectExistingOwnAccountRequest$outboundSchema: z.ZodMiniType<
  ConnectExistingOwnAccountRequest$Outbound,
  ConnectExistingOwnAccountRequest
> = z.pipe(
  z.object({
    accountId: z.string(),
    active: z.optional(z.boolean()),
    carrier: z.string(),
    metadata: z.optional(z.string()),
    parameters: z.union([
      UPSConnectExistingOwnAccountParameters$outboundSchema,
      FedExConnectExistingOwnAccountParameters$outboundSchema,
      z.record(z.string(), z.any()),
    ]),
    test: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      accountId: "account_id",
    });
  }),
);

export function connectExistingOwnAccountRequestToJSON(
  connectExistingOwnAccountRequest: ConnectExistingOwnAccountRequest,
): string {
  return JSON.stringify(
    ConnectExistingOwnAccountRequest$outboundSchema.parse(
      connectExistingOwnAccountRequest,
    ),
  );
}
