/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  FedExConnectExistingOwnAccountParameters,
  FedExConnectExistingOwnAccountParameters$inboundSchema,
  FedExConnectExistingOwnAccountParameters$Outbound,
  FedExConnectExistingOwnAccountParameters$outboundSchema,
} from "./fedexconnectexistingownaccountparameters.js";
import {
  UPSConnectExistingOwnAccountParameters,
  UPSConnectExistingOwnAccountParameters$inboundSchema,
  UPSConnectExistingOwnAccountParameters$Outbound,
  UPSConnectExistingOwnAccountParameters$outboundSchema,
} from "./upsconnectexistingownaccountparameters.js";

export type ConnectExistingOwnAccountRequestParameters =
  | FedExConnectExistingOwnAccountParameters
  | UPSConnectExistingOwnAccountParameters
  | { [k: string]: any };

export type ConnectExistingOwnAccountRequest = {
  accountId: string;
  active?: boolean | undefined;
  carrier: string;
  metadata?: string | undefined;
  parameters:
    | FedExConnectExistingOwnAccountParameters
    | UPSConnectExistingOwnAccountParameters
    | { [k: string]: any };
  test?: boolean | undefined;
};

/** @internal */
export const ConnectExistingOwnAccountRequestParameters$inboundSchema:
  z.ZodType<ConnectExistingOwnAccountRequestParameters, z.ZodTypeDef, unknown> =
    z.union([
      FedExConnectExistingOwnAccountParameters$inboundSchema,
      UPSConnectExistingOwnAccountParameters$inboundSchema,
      z.record(z.any()),
    ]);

/** @internal */
export type ConnectExistingOwnAccountRequestParameters$Outbound =
  | FedExConnectExistingOwnAccountParameters$Outbound
  | UPSConnectExistingOwnAccountParameters$Outbound
  | { [k: string]: any };

/** @internal */
export const ConnectExistingOwnAccountRequestParameters$outboundSchema:
  z.ZodType<
    ConnectExistingOwnAccountRequestParameters$Outbound,
    z.ZodTypeDef,
    ConnectExistingOwnAccountRequestParameters
  > = z.union([
    FedExConnectExistingOwnAccountParameters$outboundSchema,
    UPSConnectExistingOwnAccountParameters$outboundSchema,
    z.record(z.any()),
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConnectExistingOwnAccountRequestParameters$ {
  /** @deprecated use `ConnectExistingOwnAccountRequestParameters$inboundSchema` instead. */
  export const inboundSchema =
    ConnectExistingOwnAccountRequestParameters$inboundSchema;
  /** @deprecated use `ConnectExistingOwnAccountRequestParameters$outboundSchema` instead. */
  export const outboundSchema =
    ConnectExistingOwnAccountRequestParameters$outboundSchema;
  /** @deprecated use `ConnectExistingOwnAccountRequestParameters$Outbound` instead. */
  export type Outbound = ConnectExistingOwnAccountRequestParameters$Outbound;
}

/** @internal */
export const ConnectExistingOwnAccountRequest$inboundSchema: z.ZodType<
  ConnectExistingOwnAccountRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  account_id: z.string(),
  active: z.boolean().optional(),
  carrier: z.string(),
  metadata: z.string().optional(),
  parameters: z.union([
    FedExConnectExistingOwnAccountParameters$inboundSchema,
    UPSConnectExistingOwnAccountParameters$inboundSchema,
    z.record(z.any()),
  ]),
  test: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "account_id": "accountId",
  });
});

/** @internal */
export type ConnectExistingOwnAccountRequest$Outbound = {
  account_id: string;
  active?: boolean | undefined;
  carrier: string;
  metadata?: string | undefined;
  parameters:
    | FedExConnectExistingOwnAccountParameters$Outbound
    | UPSConnectExistingOwnAccountParameters$Outbound
    | { [k: string]: any };
  test?: boolean | undefined;
};

/** @internal */
export const ConnectExistingOwnAccountRequest$outboundSchema: z.ZodType<
  ConnectExistingOwnAccountRequest$Outbound,
  z.ZodTypeDef,
  ConnectExistingOwnAccountRequest
> = z.object({
  accountId: z.string(),
  active: z.boolean().optional(),
  carrier: z.string(),
  metadata: z.string().optional(),
  parameters: z.union([
    FedExConnectExistingOwnAccountParameters$outboundSchema,
    UPSConnectExistingOwnAccountParameters$outboundSchema,
    z.record(z.any()),
  ]),
  test: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    accountId: "account_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConnectExistingOwnAccountRequest$ {
  /** @deprecated use `ConnectExistingOwnAccountRequest$inboundSchema` instead. */
  export const inboundSchema = ConnectExistingOwnAccountRequest$inboundSchema;
  /** @deprecated use `ConnectExistingOwnAccountRequest$outboundSchema` instead. */
  export const outboundSchema = ConnectExistingOwnAccountRequest$outboundSchema;
  /** @deprecated use `ConnectExistingOwnAccountRequest$Outbound` instead. */
  export type Outbound = ConnectExistingOwnAccountRequest$Outbound;
}
