/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CustomsItem,
  CustomsItem$inboundSchema,
  CustomsItem$Outbound,
  CustomsItem$outboundSchema,
} from "./customsitem.js";

export type CustomsItemPaginatedList = {
  next?: string | undefined;
  previous?: string | undefined;
  results?: Array<CustomsItem> | undefined;
};

/** @internal */
export const CustomsItemPaginatedList$inboundSchema: z.ZodType<
  CustomsItemPaginatedList,
  z.ZodTypeDef,
  unknown
> = z.object({
  next: z.string().optional(),
  previous: z.string().optional(),
  results: z.array(CustomsItem$inboundSchema).optional(),
});

/** @internal */
export type CustomsItemPaginatedList$Outbound = {
  next?: string | undefined;
  previous?: string | undefined;
  results?: Array<CustomsItem$Outbound> | undefined;
};

/** @internal */
export const CustomsItemPaginatedList$outboundSchema: z.ZodType<
  CustomsItemPaginatedList$Outbound,
  z.ZodTypeDef,
  CustomsItemPaginatedList
> = z.object({
  next: z.string().optional(),
  previous: z.string().optional(),
  results: z.array(CustomsItem$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomsItemPaginatedList$ {
  /** @deprecated use `CustomsItemPaginatedList$inboundSchema` instead. */
  export const inboundSchema = CustomsItemPaginatedList$inboundSchema;
  /** @deprecated use `CustomsItemPaginatedList$outboundSchema` instead. */
  export const outboundSchema = CustomsItemPaginatedList$outboundSchema;
  /** @deprecated use `CustomsItemPaginatedList$Outbound` instead. */
  export type Outbound = CustomsItemPaginatedList$Outbound;
}
