/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { AddressImporter, AddressImporter$ } from "./addressimporter";
import { CustomsItemBase, CustomsItemBase$ } from "./customsitembase";
import * as z from "zod";

/**
 * B13A Option details are obtained by filing a B13A Canada Export Declaration via the Canadian Export Reporting System (CERS).
 *
 * @remarks
 * <a href="https://www.cbsa-asfc.gc.ca/services/export/guide-eng.html" target="_blank" rel="noopener noreferrer"> More information on reporting commercial exports from Canada. </a>
 */
export enum CustomsDeclarationCreateRequestB13aFilingOption {
    FiledElectronically = "FILED_ELECTRONICALLY",
    SummaryReporting = "SUMMARY_REPORTING",
    NotRequired = "NOT_REQUIRED",
}

/**
 * Type of goods of the shipment.
 */
export enum CustomsDeclarationCreateRequestContentsType {
    Documents = "DOCUMENTS",
    Gift = "GIFT",
    Sample = "SAMPLE",
    Merchandise = "MERCHANDISE",
    HumanitarianDonation = "HUMANITARIAN_DONATION",
    ReturnMerchandise = "RETURN_MERCHANDISE",
    Other = "OTHER",
}

/**
 * EEL / PFC type of the shipment. For most shipments from the US to CA, `NOEEI_30_36` is applicable; for most
 *
 * @remarks
 * other shipments from the US, `NOEEI_30_37_a` is applicable.
 */
export enum CustomsDeclarationCreateRequestEelPfc {
    NOEEI3037A = "NOEEI_30_37_a",
    NOEEI3037H = "NOEEI_30_37_h",
    NOEEI3037F = "NOEEI_30_37_f",
    Noeei3036 = "NOEEI_30_36",
    AesItn = "AES_ITN",
}

/**
 * The incoterm reference of the shipment. FCA is available for DHL Express and FedEx only.
 *
 * @remarks
 * eDAP is available for DPD UK only. DAP is available for DHL Express and DPD UK.
 * If expecting DAP for other carriers, please use DDU.
 */
export enum CustomsDeclarationCreateRequestIncoterm {
    Ddp = "DDP",
    Ddu = "DDU",
    Fca = "FCA",
    Dap = "DAP",
    EDAP = "eDAP",
}

/**
 * Indicates how the carrier should proceed in case the shipment can't be delivered.
 */
export enum CustomsDeclarationCreateRequestNonDeliveryOption {
    Abandon = "ABANDON",
    Return = "RETURN",
}

export type CustomsDeclarationCreateRequest = {
    /**
     * **required if eel_pfc is `AES_ITN`**<br>
     *
     * @remarks
     * AES / ITN reference of the shipment.
     */
    aesItn?: string | undefined;
    /**
     * B13A Option details are obtained by filing a B13A Canada Export Declaration via the Canadian Export Reporting System (CERS).
     *
     * @remarks
     * <a href="https://www.cbsa-asfc.gc.ca/services/export/guide-eng.html" target="_blank" rel="noopener noreferrer"> More information on reporting commercial exports from Canada. </a>
     */
    b13aFilingOption?: CustomsDeclarationCreateRequestB13aFilingOption | undefined;
    /**
     * **must be provided if and only if b13a_filing_option is provided**<br>
     *
     * @remarks
     * Represents:<br> the Proof of Report (POR) Number when b13a_filing_option is `FILED_ELECTRONICALLY`;<br>
     * the Summary ID Number when b13a_filing_option is `SUMMARY_REPORTING`;<br>
     * or the Exemption Number when b13a_filing_option is `NOT_REQUIRED`.
     */
    b13aNumber?: string | undefined;
    /**
     * Certificate reference of the shipment.
     */
    certificate?: string | undefined;
    /**
     * Expresses that the certify_signer has provided all information of this customs declaration truthfully.
     */
    certify: boolean;
    /**
     * Name of the person who created the customs declaration and is responsible for the validity of all
     *
     * @remarks
     * information provided.
     */
    certifySigner: string;
    commercialInvoice?: string | undefined;
    /**
     * **required if contents_type is `OTHER`**<br>
     *
     * @remarks
     * Explanation of the type of goods of the shipment.
     */
    contentsExplanation?: string | undefined;
    /**
     * Type of goods of the shipment.
     */
    contentsType: CustomsDeclarationCreateRequestContentsType;
    /**
     * Disclaimer for the shipment and customs information that have been provided.
     */
    disclaimer?: string | undefined;
    /**
     * EEL / PFC type of the shipment. For most shipments from the US to CA, `NOEEI_30_36` is applicable; for most
     *
     * @remarks
     * other shipments from the US, `NOEEI_30_37_a` is applicable.
     */
    eelPfc?: CustomsDeclarationCreateRequestEelPfc | undefined;
    /**
     * Exporter reference of an export shipment.
     */
    exporterReference?: string | undefined;
    /**
     * Importer reference of an import shipment.
     */
    importerReference?: string | undefined;
    /**
     * The incoterm reference of the shipment. FCA is available for DHL Express and FedEx only.
     *
     * @remarks
     * eDAP is available for DPD UK only. DAP is available for DHL Express and DPD UK.
     * If expecting DAP for other carriers, please use DDU.
     */
    incoterm?: CustomsDeclarationCreateRequestIncoterm | undefined;
    /**
     * Indicates whether the shipment's destination VAT has been collected. May be required for some destinations.
     */
    isVatCollected?: any | undefined;
    /**
     * Invoice reference of the shipment.
     */
    invoice?: string | undefined;
    /**
     * License reference of the shipment.
     */
    license?: string | undefined;
    /**
     * A string of up to 100 characters that can be filled with any additional information you
     *
     * @remarks
     * want to attach to the object.
     */
    metadata?: string | undefined;
    /**
     * Indicates how the carrier should proceed in case the shipment can't be delivered.
     */
    nonDeliveryOption: CustomsDeclarationCreateRequestNonDeliveryOption;
    /**
     * Additional notes to be included in the customs declaration.
     */
    notes?: string | undefined;
    /**
     * Object that represents the address of the importer
     */
    addressImporter?: AddressImporter | undefined;
    items: Array<CustomsItemBase>;
    test?: boolean | undefined;
};

/** @internal */
export const CustomsDeclarationCreateRequestB13aFilingOption$ = z.nativeEnum(
    CustomsDeclarationCreateRequestB13aFilingOption
);

/** @internal */
export const CustomsDeclarationCreateRequestContentsType$ = z.nativeEnum(
    CustomsDeclarationCreateRequestContentsType
);

/** @internal */
export const CustomsDeclarationCreateRequestEelPfc$ = z.nativeEnum(
    CustomsDeclarationCreateRequestEelPfc
);

/** @internal */
export const CustomsDeclarationCreateRequestIncoterm$ = z.nativeEnum(
    CustomsDeclarationCreateRequestIncoterm
);

/** @internal */
export const CustomsDeclarationCreateRequestNonDeliveryOption$ = z.nativeEnum(
    CustomsDeclarationCreateRequestNonDeliveryOption
);

/** @internal */
export namespace CustomsDeclarationCreateRequest$ {
    export type Inbound = {
        aes_itn?: string | undefined;
        b13a_filing_option?: CustomsDeclarationCreateRequestB13aFilingOption | undefined;
        b13a_number?: string | undefined;
        certificate?: string | undefined;
        certify: boolean;
        certify_signer: string;
        commercial_invoice?: string | undefined;
        contents_explanation?: string | undefined;
        contents_type: CustomsDeclarationCreateRequestContentsType;
        disclaimer?: string | undefined;
        eel_pfc?: CustomsDeclarationCreateRequestEelPfc | undefined;
        exporter_reference?: string | undefined;
        importer_reference?: string | undefined;
        incoterm?: CustomsDeclarationCreateRequestIncoterm | undefined;
        is_vat_collected?: any | undefined;
        invoice?: string | undefined;
        license?: string | undefined;
        metadata?: string | undefined;
        non_delivery_option: CustomsDeclarationCreateRequestNonDeliveryOption;
        notes?: string | undefined;
        address_importer?: AddressImporter$.Inbound | undefined;
        items: Array<CustomsItemBase$.Inbound>;
        test?: boolean | undefined;
    };

    export const inboundSchema: z.ZodType<CustomsDeclarationCreateRequest, z.ZodTypeDef, Inbound> =
        z
            .object({
                aes_itn: z.string().optional(),
                b13a_filing_option: CustomsDeclarationCreateRequestB13aFilingOption$.optional(),
                b13a_number: z.string().optional(),
                certificate: z.string().optional(),
                certify: z.boolean(),
                certify_signer: z.string(),
                commercial_invoice: z.string().optional(),
                contents_explanation: z.string().optional(),
                contents_type: CustomsDeclarationCreateRequestContentsType$,
                disclaimer: z.string().optional(),
                eel_pfc: CustomsDeclarationCreateRequestEelPfc$.optional(),
                exporter_reference: z.string().optional(),
                importer_reference: z.string().optional(),
                incoterm: CustomsDeclarationCreateRequestIncoterm$.optional(),
                is_vat_collected: z.any().optional(),
                invoice: z.string().optional(),
                license: z.string().optional(),
                metadata: z.string().optional(),
                non_delivery_option: CustomsDeclarationCreateRequestNonDeliveryOption$,
                notes: z.string().optional(),
                address_importer: AddressImporter$.inboundSchema.optional(),
                items: z.array(CustomsItemBase$.inboundSchema),
                test: z.boolean().optional(),
            })
            .transform((v) => {
                return {
                    ...(v.aes_itn === undefined ? null : { aesItn: v.aes_itn }),
                    ...(v.b13a_filing_option === undefined
                        ? null
                        : { b13aFilingOption: v.b13a_filing_option }),
                    ...(v.b13a_number === undefined ? null : { b13aNumber: v.b13a_number }),
                    ...(v.certificate === undefined ? null : { certificate: v.certificate }),
                    certify: v.certify,
                    certifySigner: v.certify_signer,
                    ...(v.commercial_invoice === undefined
                        ? null
                        : { commercialInvoice: v.commercial_invoice }),
                    ...(v.contents_explanation === undefined
                        ? null
                        : { contentsExplanation: v.contents_explanation }),
                    contentsType: v.contents_type,
                    ...(v.disclaimer === undefined ? null : { disclaimer: v.disclaimer }),
                    ...(v.eel_pfc === undefined ? null : { eelPfc: v.eel_pfc }),
                    ...(v.exporter_reference === undefined
                        ? null
                        : { exporterReference: v.exporter_reference }),
                    ...(v.importer_reference === undefined
                        ? null
                        : { importerReference: v.importer_reference }),
                    ...(v.incoterm === undefined ? null : { incoterm: v.incoterm }),
                    ...(v.is_vat_collected === undefined
                        ? null
                        : { isVatCollected: v.is_vat_collected }),
                    ...(v.invoice === undefined ? null : { invoice: v.invoice }),
                    ...(v.license === undefined ? null : { license: v.license }),
                    ...(v.metadata === undefined ? null : { metadata: v.metadata }),
                    nonDeliveryOption: v.non_delivery_option,
                    ...(v.notes === undefined ? null : { notes: v.notes }),
                    ...(v.address_importer === undefined
                        ? null
                        : { addressImporter: v.address_importer }),
                    items: v.items,
                    ...(v.test === undefined ? null : { test: v.test }),
                };
            });

    export type Outbound = {
        aes_itn?: string | undefined;
        b13a_filing_option?: CustomsDeclarationCreateRequestB13aFilingOption | undefined;
        b13a_number?: string | undefined;
        certificate?: string | undefined;
        certify: boolean;
        certify_signer: string;
        commercial_invoice?: string | undefined;
        contents_explanation?: string | undefined;
        contents_type: CustomsDeclarationCreateRequestContentsType;
        disclaimer?: string | undefined;
        eel_pfc?: CustomsDeclarationCreateRequestEelPfc | undefined;
        exporter_reference?: string | undefined;
        importer_reference?: string | undefined;
        incoterm?: CustomsDeclarationCreateRequestIncoterm | undefined;
        is_vat_collected?: any | undefined;
        invoice?: string | undefined;
        license?: string | undefined;
        metadata?: string | undefined;
        non_delivery_option: CustomsDeclarationCreateRequestNonDeliveryOption;
        notes?: string | undefined;
        address_importer?: AddressImporter$.Outbound | undefined;
        items: Array<CustomsItemBase$.Outbound>;
        test?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CustomsDeclarationCreateRequest
    > = z
        .object({
            aesItn: z.string().optional(),
            b13aFilingOption: CustomsDeclarationCreateRequestB13aFilingOption$.optional(),
            b13aNumber: z.string().optional(),
            certificate: z.string().optional(),
            certify: z.boolean(),
            certifySigner: z.string(),
            commercialInvoice: z.string().optional(),
            contentsExplanation: z.string().optional(),
            contentsType: CustomsDeclarationCreateRequestContentsType$,
            disclaimer: z.string().optional(),
            eelPfc: CustomsDeclarationCreateRequestEelPfc$.optional(),
            exporterReference: z.string().optional(),
            importerReference: z.string().optional(),
            incoterm: CustomsDeclarationCreateRequestIncoterm$.optional(),
            isVatCollected: z.any().optional(),
            invoice: z.string().optional(),
            license: z.string().optional(),
            metadata: z.string().optional(),
            nonDeliveryOption: CustomsDeclarationCreateRequestNonDeliveryOption$,
            notes: z.string().optional(),
            addressImporter: AddressImporter$.outboundSchema.optional(),
            items: z.array(CustomsItemBase$.outboundSchema),
            test: z.boolean().optional(),
        })
        .transform((v) => {
            return {
                ...(v.aesItn === undefined ? null : { aes_itn: v.aesItn }),
                ...(v.b13aFilingOption === undefined
                    ? null
                    : { b13a_filing_option: v.b13aFilingOption }),
                ...(v.b13aNumber === undefined ? null : { b13a_number: v.b13aNumber }),
                ...(v.certificate === undefined ? null : { certificate: v.certificate }),
                certify: v.certify,
                certify_signer: v.certifySigner,
                ...(v.commercialInvoice === undefined
                    ? null
                    : { commercial_invoice: v.commercialInvoice }),
                ...(v.contentsExplanation === undefined
                    ? null
                    : { contents_explanation: v.contentsExplanation }),
                contents_type: v.contentsType,
                ...(v.disclaimer === undefined ? null : { disclaimer: v.disclaimer }),
                ...(v.eelPfc === undefined ? null : { eel_pfc: v.eelPfc }),
                ...(v.exporterReference === undefined
                    ? null
                    : { exporter_reference: v.exporterReference }),
                ...(v.importerReference === undefined
                    ? null
                    : { importer_reference: v.importerReference }),
                ...(v.incoterm === undefined ? null : { incoterm: v.incoterm }),
                ...(v.isVatCollected === undefined ? null : { is_vat_collected: v.isVatCollected }),
                ...(v.invoice === undefined ? null : { invoice: v.invoice }),
                ...(v.license === undefined ? null : { license: v.license }),
                ...(v.metadata === undefined ? null : { metadata: v.metadata }),
                non_delivery_option: v.nonDeliveryOption,
                ...(v.notes === undefined ? null : { notes: v.notes }),
                ...(v.addressImporter === undefined
                    ? null
                    : { address_importer: v.addressImporter }),
                items: v.items,
                ...(v.test === undefined ? null : { test: v.test }),
            };
        });
}
