/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type EmbeddedAuthorizationRequest = {
  /**
   * The scope requested for the token.
   */
  scope: string;
};

/** @internal */
export type EmbeddedAuthorizationRequest$Outbound = {
  scope: string;
};

/** @internal */
export const EmbeddedAuthorizationRequest$outboundSchema: z.ZodMiniType<
  EmbeddedAuthorizationRequest$Outbound,
  EmbeddedAuthorizationRequest
> = z.object({
  scope: z.string(),
});

export function embeddedAuthorizationRequestToJSON(
  embeddedAuthorizationRequest: EmbeddedAuthorizationRequest,
): string {
  return JSON.stringify(
    EmbeddedAuthorizationRequest$outboundSchema.parse(
      embeddedAuthorizationRequest,
    ),
  );
}
