/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

/**
 * Current state of the order. See the <a href="https://docs.goshippo.com/docs/orders/orders/">orders tutorial</a>
 *
 * @remarks
 * for the logic of how the status is handled.
 */
export const OrderStatusEnum = {
    Unknown: "UNKNOWN",
    Awaitpay: "AWAITPAY",
    Paid: "PAID",
    Refunded: "REFUNDED",
    Cancelled: "CANCELLED",
    PartiallyFulfilled: "PARTIALLY_FULFILLED",
    Shipped: "SHIPPED",
} as const;
/**
 * Current state of the order. See the <a href="https://docs.goshippo.com/docs/orders/orders/">orders tutorial</a>
 *
 * @remarks
 * for the logic of how the status is handled.
 */
export type OrderStatusEnum = ClosedEnum<typeof OrderStatusEnum>;

/** @internal */
export namespace OrderStatusEnum$ {
    export const inboundSchema: z.ZodNativeEnum<typeof OrderStatusEnum> =
        z.nativeEnum(OrderStatusEnum);
    export const outboundSchema: z.ZodNativeEnum<typeof OrderStatusEnum> = inboundSchema;
}
