/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Platform the order was created on and, if applicable, imported from.
 *
 * @remarks
 * Orders created via the Shippo API or dashboard will have the value "Shippo".
 */
export const OrderShopAppEnum = {
  Amazon: "Amazon",
  Bigcommerce: "Bigcommerce",
  CSVImport: "CSV_Import",
  EBay: "eBay",
  EPages: "ePages",
  Etsy: "Etsy",
  Godaddy: "Godaddy",
  Magento: "Magento",
  Shippo: "Shippo",
  Shopify: "Shopify",
  Spreecommerce: "Spreecommerce",
  StripeRelay: "StripeRelay",
  Walmart: "Walmart",
  Weebly: "Weebly",
  WooCommerce: "WooCommerce",
} as const;
/**
 * Platform the order was created on and, if applicable, imported from.
 *
 * @remarks
 * Orders created via the Shippo API or dashboard will have the value "Shippo".
 */
export type OrderShopAppEnum = ClosedEnum<typeof OrderShopAppEnum>;

/** @internal */
export const OrderShopAppEnum$inboundSchema: z.ZodMiniEnum<
  typeof OrderShopAppEnum
> = z.enum(OrderShopAppEnum);
/** @internal */
export const OrderShopAppEnum$outboundSchema: z.ZodMiniEnum<
  typeof OrderShopAppEnum
> = OrderShopAppEnum$inboundSchema;
