/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * |Token | Name | Dimensions|
 *
 * @remarks
 * |:---|:---|:---|
 * | couriersplease_500g_satchel | 500g Satchel | 22.00 x 33.50 x 0.10 cm|
 * | couriersplease_1kg_satchel | 1kg Satchel | 28.00 x 35.00 x 0.10 cm|
 * | couriersplease_3kg_satchel | 3kg Satchel | 34.00 x 42.00 x 0.10 cm|
 * | couriersplease_5kg_satchel | 5kg Satchel | 43.70 x 59.70 x 0.10 cm|
 */
export const ParcelTemplateCouriersPleaseEnum = {
  Couriersplease500gSatchel: "couriersplease_500g_satchel",
  Couriersplease1kgSatchel: "couriersplease_1kg_satchel",
  Couriersplease3kgSatchel: "couriersplease_3kg_satchel",
  Couriersplease5kgSatchel: "couriersplease_5kg_satchel",
} as const;
/**
 * |Token | Name | Dimensions|
 *
 * @remarks
 * |:---|:---|:---|
 * | couriersplease_500g_satchel | 500g Satchel | 22.00 x 33.50 x 0.10 cm|
 * | couriersplease_1kg_satchel | 1kg Satchel | 28.00 x 35.00 x 0.10 cm|
 * | couriersplease_3kg_satchel | 3kg Satchel | 34.00 x 42.00 x 0.10 cm|
 * | couriersplease_5kg_satchel | 5kg Satchel | 43.70 x 59.70 x 0.10 cm|
 */
export type ParcelTemplateCouriersPleaseEnum = ClosedEnum<
  typeof ParcelTemplateCouriersPleaseEnum
>;

/** @internal */
export const ParcelTemplateCouriersPleaseEnum$inboundSchema: z.ZodNativeEnum<
  typeof ParcelTemplateCouriersPleaseEnum
> = z.nativeEnum(ParcelTemplateCouriersPleaseEnum);

/** @internal */
export const ParcelTemplateCouriersPleaseEnum$outboundSchema: z.ZodNativeEnum<
  typeof ParcelTemplateCouriersPleaseEnum
> = ParcelTemplateCouriersPleaseEnum$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ParcelTemplateCouriersPleaseEnum$ {
  /** @deprecated use `ParcelTemplateCouriersPleaseEnum$inboundSchema` instead. */
  export const inboundSchema = ParcelTemplateCouriersPleaseEnum$inboundSchema;
  /** @deprecated use `ParcelTemplateCouriersPleaseEnum$outboundSchema` instead. */
  export const outboundSchema = ParcelTemplateCouriersPleaseEnum$outboundSchema;
}
