/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * |Token | Name | Dimensions|
 *
 * @remarks
 * |:---|:---|:---|
 * | DHLeC_Irregular | Irregular Shipment | 10.00 x 10.00 x 10.00 in|
 * | DHLeC_SM_Flats | Flats | 27.00 x 17.00 x 17.00 in|
 */
export const ParcelTemplateDHLeCommerceEnum = {
  DHLeCIrregular: "DHLeC_Irregular",
  DHLeCSMFlats: "DHLeC_SM_Flats",
} as const;
/**
 * |Token | Name | Dimensions|
 *
 * @remarks
 * |:---|:---|:---|
 * | DHLeC_Irregular | Irregular Shipment | 10.00 x 10.00 x 10.00 in|
 * | DHLeC_SM_Flats | Flats | 27.00 x 17.00 x 17.00 in|
 */
export type ParcelTemplateDHLeCommerceEnum = ClosedEnum<
  typeof ParcelTemplateDHLeCommerceEnum
>;

/** @internal */
export const ParcelTemplateDHLeCommerceEnum$inboundSchema: z.ZodMiniEnum<
  typeof ParcelTemplateDHLeCommerceEnum
> = z.enum(ParcelTemplateDHLeCommerceEnum);
/** @internal */
export const ParcelTemplateDHLeCommerceEnum$outboundSchema: z.ZodMiniEnum<
  typeof ParcelTemplateDHLeCommerceEnum
> = ParcelTemplateDHLeCommerceEnum$inboundSchema;
