/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Rate, Rate$inboundSchema } from "./rate.js";

export type RatePaginatedList = {
  next?: string | undefined;
  previous?: string | undefined;
  results?: Array<Rate> | undefined;
};

/** @internal */
export const RatePaginatedList$inboundSchema: z.ZodMiniType<
  RatePaginatedList,
  unknown
> = z.object({
  next: z.optional(z.string()),
  previous: z.optional(z.string()),
  results: z.optional(z.array(Rate$inboundSchema)),
});

export function ratePaginatedListFromJSON(
  jsonString: string,
): SafeParseResult<RatePaginatedList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RatePaginatedList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RatePaginatedList' from JSON`,
  );
}
