/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * |Token | Service name|
 *
 * @remarks
 * |:---|:---|
 * | same_day | Next Day|
 * | next_day | Next Day|
 */
export const ServiceLevelSwyftEnum = {
  SameDay: "same_day",
  NextDay: "next_day",
} as const;
/**
 * |Token | Service name|
 *
 * @remarks
 * |:---|:---|
 * | same_day | Next Day|
 * | next_day | Next Day|
 */
export type ServiceLevelSwyftEnum = ClosedEnum<typeof ServiceLevelSwyftEnum>;

/** @internal */
export const ServiceLevelSwyftEnum$inboundSchema: z.ZodNativeEnum<
  typeof ServiceLevelSwyftEnum
> = z.nativeEnum(ServiceLevelSwyftEnum);

/** @internal */
export const ServiceLevelSwyftEnum$outboundSchema: z.ZodNativeEnum<
  typeof ServiceLevelSwyftEnum
> = ServiceLevelSwyftEnum$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ServiceLevelSwyftEnum$ {
  /** @deprecated use `ServiceLevelSwyftEnum$inboundSchema` instead. */
  export const inboundSchema = ServiceLevelSwyftEnum$inboundSchema;
  /** @deprecated use `ServiceLevelSwyftEnum$outboundSchema` instead. */
  export const outboundSchema = ServiceLevelSwyftEnum$outboundSchema;
}
