/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * |Token | Service name|
 *
 * @remarks
 * |:---|:---|
 * | dhl_germany_europaket | DHL Germany Europaket|
 * | dhl_germany_paket | DHL Germany Paket|
 * | dhl_germany_paket_connect | DHL Germany Paket Connect|
 * | dhl_germany_paket_international | DHL Germany Paket International|
 * | dhl_germany_paket_priority | DHL Germany Paket Priority|
 * | dhl_germany_paket_sameday | DHL Germany Paket Sameday|
 */
export const ServiceLevelDHLGermanyEnum = {
  DhlGermanyEuropaket: "dhl_germany_europaket",
  DhlGermanyPaket: "dhl_germany_paket",
  DhlGermanyPaketConnect: "dhl_germany_paket_connect",
  DhlGermanyPaketInternational: "dhl_germany_paket_international",
  DhlGermanyPaketPriority: "dhl_germany_paket_priority",
  DhlGermanyPaketSameday: "dhl_germany_paket_sameday",
} as const;
/**
 * |Token | Service name|
 *
 * @remarks
 * |:---|:---|
 * | dhl_germany_europaket | DHL Germany Europaket|
 * | dhl_germany_paket | DHL Germany Paket|
 * | dhl_germany_paket_connect | DHL Germany Paket Connect|
 * | dhl_germany_paket_international | DHL Germany Paket International|
 * | dhl_germany_paket_priority | DHL Germany Paket Priority|
 * | dhl_germany_paket_sameday | DHL Germany Paket Sameday|
 */
export type ServiceLevelDHLGermanyEnum = ClosedEnum<
  typeof ServiceLevelDHLGermanyEnum
>;

/** @internal */
export const ServiceLevelDHLGermanyEnum$inboundSchema: z.ZodMiniEnum<
  typeof ServiceLevelDHLGermanyEnum
> = z.enum(ServiceLevelDHLGermanyEnum);
/** @internal */
export const ServiceLevelDHLGermanyEnum$outboundSchema: z.ZodMiniEnum<
  typeof ServiceLevelDHLGermanyEnum
> = ServiceLevelDHLGermanyEnum$inboundSchema;
