/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const ShipmentExtraReturnServiceTypeLasershipEnum = {
  NoReturn: "NO_RETURN",
} as const;
export type ShipmentExtraReturnServiceTypeLasershipEnum = ClosedEnum<
  typeof ShipmentExtraReturnServiceTypeLasershipEnum
>;

/** @internal */
export const ShipmentExtraReturnServiceTypeLasershipEnum$inboundSchema:
  z.ZodMiniEnum<typeof ShipmentExtraReturnServiceTypeLasershipEnum> = z.enum(
    ShipmentExtraReturnServiceTypeLasershipEnum,
  );
/** @internal */
export const ShipmentExtraReturnServiceTypeLasershipEnum$outboundSchema:
  z.ZodMiniEnum<typeof ShipmentExtraReturnServiceTypeLasershipEnum> =
    ShipmentExtraReturnServiceTypeLasershipEnum$inboundSchema;
