/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const ShipmentExtraLasershipAttributesEnum = {
  TwoPersonDelivery: "TwoPersonDelivery",
  Explosive: "Explosive",
  Alcohol: "Alcohol",
  Hazmat: "Hazmat",
  ControlledSubstance: "ControlledSubstance",
  Refrigerated: "Refrigerated",
  DryIce: "DryIce",
  Perishable: "Perishable",
  NoRTS: "NoRTS",
} as const;
export type ShipmentExtraLasershipAttributesEnum = ClosedEnum<
  typeof ShipmentExtraLasershipAttributesEnum
>;

/** @internal */
export const ShipmentExtraLasershipAttributesEnum$inboundSchema: z.ZodMiniEnum<
  typeof ShipmentExtraLasershipAttributesEnum
> = z.enum(ShipmentExtraLasershipAttributesEnum);
/** @internal */
export const ShipmentExtraLasershipAttributesEnum$outboundSchema: z.ZodMiniEnum<
  typeof ShipmentExtraLasershipAttributesEnum
> = ShipmentExtraLasershipAttributesEnum$inboundSchema;
