/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const ShipmentExtraReturnServiceTypeUPSEnum = {
  PrintAndMail: "PRINT_AND_MAIL",
  Attempt1: "ATTEMPT_1",
  Attempt3: "ATTEMPT_3",
  ElectronicLabel: "ELECTRONIC_LABEL",
} as const;
export type ShipmentExtraReturnServiceTypeUPSEnum = ClosedEnum<
  typeof ShipmentExtraReturnServiceTypeUPSEnum
>;

/** @internal */
export const ShipmentExtraReturnServiceTypeUPSEnum$inboundSchema: z.ZodMiniEnum<
  typeof ShipmentExtraReturnServiceTypeUPSEnum
> = z.enum(ShipmentExtraReturnServiceTypeUPSEnum);
/** @internal */
export const ShipmentExtraReturnServiceTypeUPSEnum$outboundSchema:
  z.ZodMiniEnum<typeof ShipmentExtraReturnServiceTypeUPSEnum> =
    ShipmentExtraReturnServiceTypeUPSEnum$inboundSchema;
