/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * A finer-grained classification of the tracking event.
 */
export type TrackingStatusSubstatus = {
  /**
   * A code that represents the substatus of the shipment. See the <a href="https://docs.goshippo.com/docs/tracking/tracking/#event-definitions">Event Definitions</a> for more information.
   */
  code: string;
  /**
   * A human-readable description of the substatus. See the <a href="https://docs.goshippo.com/docs/tracking/tracking/#event-definitions">Event Definitions</a> for more information.
   */
  text: string;
  /**
   * Indicates whether the substatus requires action from the shipper or recipient to complete delivery.
   */
  actionRequired: boolean;
};

/** @internal */
export const TrackingStatusSubstatus$inboundSchema: z.ZodType<
  TrackingStatusSubstatus,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  text: z.string(),
  action_required: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "action_required": "actionRequired",
  });
});

/** @internal */
export type TrackingStatusSubstatus$Outbound = {
  code: string;
  text: string;
  action_required: boolean;
};

/** @internal */
export const TrackingStatusSubstatus$outboundSchema: z.ZodType<
  TrackingStatusSubstatus$Outbound,
  z.ZodTypeDef,
  TrackingStatusSubstatus
> = z.object({
  code: z.string(),
  text: z.string(),
  actionRequired: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    actionRequired: "action_required",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TrackingStatusSubstatus$ {
  /** @deprecated use `TrackingStatusSubstatus$inboundSchema` instead. */
  export const inboundSchema = TrackingStatusSubstatus$inboundSchema;
  /** @deprecated use `TrackingStatusSubstatus$outboundSchema` instead. */
  export const outboundSchema = TrackingStatusSubstatus$outboundSchema;
  /** @deprecated use `TrackingStatusSubstatus$Outbound` instead. */
  export type Outbound = TrackingStatusSubstatus$Outbound;
}
