name: Validate

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      SHIPPO_TOKEN: ${{ secrets.SHIPPO_TOKEN }}
    concurrency:
      group: javascript-sdk-check-${{ github.event.pull_request.number }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Node
        id: setup_node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-${{ steps.setup_node.outputs.node-version }}-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: |
          make install-ci
      - name: Check
        run: make check
